### ISSUE TITLE
rocksdb: WriteBatchWithIndex: use per ColumnFamily index

### ISSUE THREAD

**Issue by rockeet** [Terark/pub-task#1]
在 WriteBatchWithIndex 中，每个 ColumnFamily 一个 Index，以减少 compare 的开销，提高总体性能。

**Comment by mm304321141** [comment]
dev done
https://github.com/Terark/rocksdb/commit/4d5eeaedeba06ff56122d0a03d25e8c510eb31c8

**Comment by rockeet** [comment]
When #13 is done, push to rocksdb official.

**Comment by rockeet** [comment]
done
